### PR TITLE
Validation Test for ENRLT Model

### PR DESCRIPTION
**Pull request by aladshaw3**
## Fixes/Addresses:

This adds a set of tests to validate with eNRLT model for a pure water and a typical carbonic acid solution. 

## Summary/Motivation:

The eNRLT model is part of the June milestone and should have a validation test in ProteusLib to show that the model is operational and can produce correct pH values when given a typical ion system for aqueous solutions. 

## Changes proposed in this PR:
- Added <code>test_enrtl_water_ph.py</code> file to validate eNRTL results

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by aladshaw3** [comment]
This test relies on changes made to IDAES very recently. Not sure if that is why it is failing the checks, but seems likely since it won't even build the basic objects I want.

**Comment by bknueven** [comment]
Since we now have an IDAES release this works against, it seems like this PR should become part of the June release.

**Comment by aladshaw3** [comment]
> Since we now have an IDAES release this works against, it seems like this PR should become part of the June release.

So, I am not sure why the checks actually passed for a minute there, but they don't now. After reviewing my conda environments, I see that the code here is dependent on idaes-pse 1.11.0.dev0, but ProteusLib is using 1.10.1. I generally use the latest dev version of IDAES because we are constantly testing and verifying all the latest and greatest chemistry submodules. 

It looks like this PR will have to wait for the next IDAES release.

**Comment by aladshaw3** [comment]
Another thing to note, although the nawi-hub fork of IDAES is up-to-date, the <code>setup.py</code> is specifically pulling in the 1.10.1 release of IDAES and not 1.11.0, which is the version I tested this code on.

**Review by lbianchi-lbl — APPROVED** [review]
This looks good to me. @aladshaw3 If that's OK for you, I'll go ahead and merge in #151 and update the required checks, so we can merge the changes from `main` and test that this PR runs on Windows as well.

**Review by TimBartholomew — APPROVED** [review]
LGTM

**Pull request merged**
