### PR TITLE
Add docs section on using pip to update existing dev environments

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Fixes/Addresses:

Adding these steps in the docs should help address present and future issues (as experienced by @aladshaw3 and @srikanthallu) when updating `proteuslib` and its dependencies in an existing development environment using pip.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by adam-a-a — APPROVED** [review]
Nice, @lbianchi-lbl ! I was just having issues myself with setting up a Linux VM and trying to get proteus going there. This is extremely helpful to have. I'm not sure (yet) if my problem will be completely fixed by running `pip --no-cache-dir install --force-reinstall -r requirements-dev.txt`, but either way, we need this in the documentation.

**Review by andrewlee94 — DISMISSED** [review]

**Comment by adam-a-a** [comment]
@lbianchi-lbl I'm not sure if you wanted to add anything to this PR. If not, we're ready to merge.

**Comment by lbianchi-lbl** [comment]
@adam-a-a As far as I'm concerned this is good to go, however it looks like the link-checking step is failing, curiously enough only for one Python version but not the others.

**Comment by adam-a-a** [comment]
> @adam-a-a As far as I'm concerned this is good to go, however it looks like the link-checking step is failing, curiously enough only for one Python version but not the others.

@lbianchi-lbl Interesting- it seems that link-checking steps were disabled for all Python versions except one; I think this was done to save time. So there's a good chance the check would fail for the other versions. The error seems to be related to a link for the Conda Installation guide. I found this link that we can try if we want to replace the old one that's resulting in the error: https://docs.conda.io/projects/conda/en/latest/user-guide/install/

**Comment by adam-a-a** [comment]
To be more precise, this is the error we are seeing:

`(getting_started/install: line   21) broken    https://conda.io/projects/conda/en/latest/user-guide/install/index.html - HTTPSConnectionPool(host='conda.io', port=443): Max retries exceeded with url: /projects/conda/en/latest/user-guide/install/index.html (Caused by SSLError(SSLCertVerificationError("hostname 'conda.io' doesn't match either of '*.readthedocs-hosted.com', 'readthedocs-hosted.com'")))`

**Review by adam-a-a — APPROVED** [review]

**Comment by lbianchi-lbl** [comment]
@adam-a-a oh, this makes sense, thanks for the clarification, and for fixing the link.

**Review by TimBartholomew — APPROVED** [review]

**Pull request merged**
