### PR TITLE
Created initial test case for seawater alkalinity

### PR DESCRIPTION
**Pull request by aladshaw3**
## Fixes/Addresses:

Integration testing for application of chemical framework to solve problem that emulates the pH, salinity, and carbonate alkalinity of seawater. 

## Summary/Motivation:

This is an early real-world test for the utilization of the IDAES chemical framework to solve realistic aqueous chemistry problems. The test sets up a simulated seawater made up of water, sodium bicarbonate, and some additional salt ions in solution at the typical concentrations found in real seawater. Chemical equilibrium is then solved using both the "inherent" reaction system and standard "equilibrium" reactions. This demonstrates that the chemical framework can solve relevant problems for NAWI/ProteusLib. 

## Changes proposed in this PR:
- Added new test file for calculations of seawater pH, salinity, and carbonate alkalinity

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by TimBartholomew** [comment]
@aladshaw3 did you test this with `pytest -m "unit or component"`, currently pytest is set up to skip tests marked with component

**Comment by Andresj89** [comment]
just a couple of questions:
1) Do we need to assert `test_initialize_inherent` and `test_initialize_equilibrium` after calling the initialize method?
2) A more general question, right now the config files are being built in the same file with the tests. Do you guys think that eventually we can build the config files straight from the data base? I think that would make our tests cleaner.

**Comment by andrewlee94** [comment]
To follow up on @Andresj89's comments - yes, every test needs to contain an assert of some sort. For cases like this where we call a solver (even if indirectly), we need to make sure the solver returned a feasible solution.

**Comment by aladshaw3** [comment]
> @aladshaw3 did you test this with `pytest -m "unit or component"`, currently pytest is set up to skip tests marked with component

Yes, I ran pytest with those options. All tests passed on my machine.

**Comment by aladshaw3** [comment]
> just a couple of questions:
> 
> 1. Do we need to assert `test_initialize_inherent` and `test_initialize_equilibrium` after calling the initialize method?
> 2. A more general question, right now the config files are being built in the same file with the tests. Do you guys think that eventually we can build the config files straight from the data base? I think that would make our tests cleaner.

@andrewlee94 

1. Is there a specific assertion I can put here? Does the initialize method in IDAES return any status information we can check?
2. Yes, eventually the config files should be built from the database. That will be in future unit tests that will live under the electrolytedb folder I assume. However, for the time being, we need these tests to ensure that the IDAES chemistry framework can solve relevant chemical problems of interest.

**Comment by andrewlee94** [comment]
@aladshaw3 Unfortunately, there is no easy or standard answer to that question. I just had a look, and in IDAES different models do different things. Notably, of the ones I looked at, none of them checked for a feasible solution (`initialize` does not return a status, which it probably should).

I suppose the correct answer is that IDAES needs to make `initialize` return a status at the end so we can confirm.

**Comment by TimBartholomew** [comment]
> @aladshaw3 Unfortunately, there is no easy or standard answer to that question. I just had a look, and in IDAES different models do different things. Notably, of the ones I looked at, none of them checked for a feasible solution (`initialize` does not return a status, which it probably should).
> 
> I suppose the correct answer is that IDAES needs to make `initialize` return a status at the end so we can confirm.

I second that!

**Comment by aladshaw3** [comment]
@Andresj89 @andrewlee94 @TimBartholomew 

Committed additional changes to this PR. Added assertions in the initialize tests following the IDAES 'test_BTIdeal.py' example. Ran all tests (both unit and component) and checked against Pyomo 6 to ensure all tests passed.

**Review by Andresj89 — APPROVED** [review]
LGTM

**Pull request merged**
