### PR TITLE
Reorganize Electrolyte Database Documentation

### PR DESCRIPTION
**Pull request by TimBartholomew**
## Fixes/Addresses:

None

## Summary/Motivation:
Current Electrolyte Database documentation was in its own high level folder broken out into the Diataxis categories. This PR integrates it with the other documentation by moving the content to the technical reference and how to sections.

## Changes proposed in this PR:
- Combined previous concepts and reference documentation into technical reference material
- Combined previous installation and example documentation into how to material
- Slight edits and modifications

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by TimBartholomew** [comment]
There is one outstanding issue, for some reason the technical reference documentation renders to a different font than the rest of the documentation.

**Comment by TimBartholomew** [comment]
@adam-a-a @dangunter, I'm aware of the test failures. They don't fail locally for me and I don't even get warnings from Sphinx. I think the failures are tied to the apidocs briefly described in #143

**Comment by adam-a-a** [comment]
@TimBartholomew I managed to get past the Read the Docs build error, so this PR should be good to go.

**Review by adam-a-a — DISMISSED** [review]

**Review by adam-a-a — APPROVED** [review]

**Review by aladshaw3 — APPROVED** [review]
LGTM

**Pull request merged**
