### PR TITLE
Update idaes-pse to latest tag on nawi-hub fork

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation:

Update prerelease dependency for `idaes-pse` in `setup.py` after fast-forwarding and tagging our `nawi-hub/idaes-pse` fork.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
It seems most of the tests are failing with the most recent tag. For a comparison between the two tags: https://github.com/nawi-hub/idaes-pse/compare/1.10.1.proteuslib.2021.07.01...nawi-hub:1.10.1.proteuslib.2021.07.22

**Comment by aladshaw3** [comment]
@andrewlee94 Looks like all test failures are linked to bad scaling of the aqueous chemistry. Most failures are solver or initailizer failures. These are indicative of poor scaling. What was changed in IDAES exactly that now makes our prior scaling work defunct?

**Comment by aladshaw3** [comment]
@andrewlee94 @srikanthallu @TimBartholomew This should not be merged in until the entire chem team can test this new IDAES code with the core chemistry modules. This new IDAES completely breaks everything we have worked on for the past few months and completely changes what our modeling and scaling strategies will be going forward. 

Unfortunately, I will have very limited time to do a deep dive on this. I am already over committed on time for the next two weeks working on proposals and other projects. This needs to wait for the time being.

**Comment by lbianchi-lbl** [comment]
Just to provide a bit more information (unfortunately purely on the software engineering side, but hopefully it can still be helpful): I ran `git bisect` to try to figure out what's the first commit in `idaes-pse` that causes one or more tests in `proteuslib` to fail, and the results seems to be [this one](https://github.com/nawi-hub/idaes-pse/commit/f9da921328a8b4f99507ba4270c453037c93b015).

The complete log is attached here: [git-bisect-2.log](https://github.com/nawi-hub/proteuslib/files/6866152/git-bisect-2.log)

**Comment by andrewlee94** [comment]
Looking through those failures, I see three different causes, two of which are more-or-less expected:

1. The calculation of density for mixtures in IDAES was corrected, which results in small changes in the calculated density. The new results should be more accurate, but do mean the tests need to be updated.
2. I saw at least one test where the difference was in the 6th significant figure of the result when testing to a relative error of 1e-5. However, the `assert` statement was only written with 4-5 significant figures, so  that small change was enough to break the tests. I would suggest always writing `assert` statements to one more significant figure than you are asserting.
3. I saw a couple of tests where the solver failed to converge for some reason, and it might be due to scaling. However, I am not sure what would have caused that behaviour - the only significant change I know of is the density calculation and that should be peripheral to the model.

@lbianchi-lbl I cannot see how that specific PR/commit would have caused any of these problems. None of our models are using those features yet.

**Comment by adam-a-a** [comment]
@aladshaw3 I was able to eliminate a couple of the failures, but there is one that I can't get through yet. Apparently, while trying to solve in `test_solve_cstr_kin`, I find the following error related to taking the log of a negative value:

`Error evaluating constraint fs.unit.control_volume.properties_out[0.0].inherent_equilibrium_constraint[H2CO3_Ka2]: can't evaluate log(-2.21051e-20).`

I should add that I tried including another test to check for poorly scaled variables and attempted to repair those poorly scaled vars. Right now, that code is commented out, but if you were to run the test with that uncommented, you'd see a similar error message, except you'd see it for a different reaction (e.g., `H20_Kw` instead of `H2CO3_Ka2`). 

Therefore, it seems that adjusting variable scaling further might resolve the error, but I am not sure to get there. @andrewlee94 tried working through a solution with me; maybe he or somebody else can make some headway with this.

**Comment by aladshaw3** [comment]
I cannot recreate the same set of errors (test errors on linux) that are being reported on my own machine, so it will be very difficult to fix this.

**Comment by aladshaw3** [comment]
@adam-a-a I was able to recreate some of the issues by creating a manual IDAES env and running the tests in their. Then, I am able to correct some of the issues by changing how the scaling is done (at least on the linux side). I have a few more issues to work out, but you will start to see the linux checks passing soon (I would imagine). 

Additional updates may be needed for Windows. The major problem with all the chemistry is that the problems are all very poorly scaled and the scaling changes from unit to unit, computer to computer. I don't think we will ever be able to do any realistic chemistry reliably unless we massively simplify what reactions we consider, how we make the equilibrium statements, and find a universal way to scale the problems.

**Review by ksbeattie — APPROVED** [review]
LGTM

**Review by ksbeattie — APPROVED** [review]

**Review by aladshaw3 — APPROVED** [review]
LGTM, I opened a PR to deal with the skipped tests. Will get to that asap.

**Pull request merged**
