### PR TITLE
Fix EDB handling of ions

### PR DESCRIPTION
**Pull request by dangunter**
## Fixes/Addresses: #163 

(replace this with the issue # fixed or addressed, if no issue exists then a brief statement of what this PR does)

## Changes proposed in this PR:

- [x] Fix data to include proper type (Solute, Solvent, Anion, Cation) and charge for cation and anions.
- [x] Fix component, reaction, base data as needed to match generated configs used in tests
- [x] Add methods as needed to modify configs after fetch from DB
- [x] Add methods to fetch from DB by additional criteria
- [x] Test with simple water reactions

 Test with simple water reactions with eNRTL -- next PR(s)!

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
@aladshaw3 (maybe @andrewlee94 ), in the test for the eNRTL water dissociation (`test_enrtl_water_pH.py`), the parameter data in the test file for the H2CO3_Ka1 and _Ka2 is different from what I have in the database (from earlier data). Should I update the database files to match, or are these alternate formulations that should both be preserved?

**Comment by dangunter** [comment]
It's not pretty, and arguably not even that good -- but it's a step forward, but I swear I will next document and test what's there, so others can maybe someday use it for real scientific/engineering tasks.

**Review by aladshaw3 — APPROVED** [review]
LGTM - I believe the handling of ions is correct now. I can dig more into the skipped tests later, which I think are unrelated to the handling of the ions.

**Review by andrewlee94 — APPROVED** [review]
I am going to assume this is good.

**Pull request merged**
