### PR TITLE
Adding reverse osmosis tutorial

### PR DESCRIPTION
**Pull request by bknueven**
## Fixes/Addresses:
Adds an RO tutorial, making progress towards #113.

## Summary/Motivation:
This is a introductory Jupyter notebook demonstrating the RO unit model with the NaCl property package.

## Changes proposed in this PR:
- Creating top-level "tutorials" directory (Question: is this the right place?)
- Adding a tutorial `reverse_osmosis_0D` (thanks to @adam-a-a)
- Set-up basic tutorial / Jupyter notebook testing
- Adding a "Tutorials" section to documentation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by TimBartholomew** [comment]
I think the top-level tutorials folder make sense. I'll approve once the tests pass.

**Comment by lbianchi-lbl** [comment]
@bknueven I'm going to try building the notebook locally as a first pass and report back.

**Comment by adam-a-a** [comment]
In addition to resolving the Read the Docs build failure, there is another warning that I saw regarding the path to the RO notebook: `proteuslib\docs\tutorials\index.rst:15: WARNING: toctree contains reference to nonexisting document 'tutorials/tutorial_notebooks/reverse_osmosis_0D'`

**Comment by bknueven** [comment]
I removed the literal inclusion of the Jupyter notebooks in the documentation for now and point the user to their location on GitHub. This isn't ideal, but I think getting the documentation properly working with Jupyter notebooks should be saved for a follow-on PR.

**Review by adam-a-a — APPROVED** [review]
LGTM!

**Review by lbianchi-lbl — APPROVED** [review]
@bknueven I've checked that the notebook runs locally. I also tried a quick attempt at integrating the setup used to build the notebooks in IDAES/examples-pse, but it will require a bit more work to function properly. This is necessary for the complete integration with the Sphinx/ReadTheDocs documentation and therefore it makes sense to defer that to a later time. In the meantime, I think the test you've written is good and will be a reasonable check until we enable the more complete solution.

**Comment by bknueven** [comment]
Thanks @lbianchi-lbl. I wonder if longer-term we shouldn't implement the full IDAES solution and keep these in a separate repository.

**Pull request merged**
